-- Inserta las coberturas del xlsx que faltaban en el catálogo (las existentes no se tocan).
INSERT INTO "Prepaga" ("id", "nombre", "nombreCompleto") VALUES
    (gen_random_uuid()::text, 'PARTICULAR', 'Particular / Consulta Privada'),
    (gen_random_uuid()::text, 'ACCORD SALUD', 'Accord Salud'),
    (gen_random_uuid()::text, 'AVALIAN', 'Avalian Cobertura Médica Integral (ex ACA Salud)'),
    (gen_random_uuid()::text, 'BOREAL', 'Boreal Cobertura de Salud'),
    (gen_random_uuid()::text, 'BRISTOL', 'Bristol Medicine'),
    (gen_random_uuid()::text, 'CEMIC', 'CEMIC'),
    (gen_random_uuid()::text, 'EMERGENCIAS', 'Emergencias Salud'),
    (gen_random_uuid()::text, 'ESENCIAL', 'Medicina Esencial'),
    (gen_random_uuid()::text, 'FEDERADA SALUD', 'Federada Salud'),
    (gen_random_uuid()::text, 'GALENO', 'Galeno Argentina'),
    (gen_random_uuid()::text, 'HOMINIS', 'Medicina Prepaga Hominis'),
    (gen_random_uuid()::text, 'HOSPITAL ALEMAN', 'Hospital Alemán'),
    (gen_random_uuid()::text, 'HOSPITAL AUSTRAL', 'Hospital Austral'),
    (gen_random_uuid()::text, 'JERARQUICOS SALUD', 'Jerárquicos Salud'),
    (gen_random_uuid()::text, 'MEDICUS', 'Medicus Medicina Prepaga'),
    (gen_random_uuid()::text, 'MEDIFE', 'Medifé Asociación Civil'),
    (gen_random_uuid()::text, 'OMINT', 'OMINT'),
    (gen_random_uuid()::text, 'OSDE', 'OSDE Binario'),
    (gen_random_uuid()::text, 'PREVENCION', 'Prevención Salud'),
    (gen_random_uuid()::text, 'SANCOR', 'SanCor Salud'),
    (gen_random_uuid()::text, 'SMG', 'Swiss Medical Medicina Privada'),
    (gen_random_uuid()::text, 'SIPSSA', 'SIPSSA Medicina Prepaga'),
    (gen_random_uuid()::text, 'PAMI / INSSJP', 'PAMI / INSSJP'),
    (gen_random_uuid()::text, 'IOMA', 'IOMA'),
    (gen_random_uuid()::text, 'IAPOS', 'IAPOS'),
    (gen_random_uuid()::text, 'IOSCOR', 'IOSCOR'),
    (gen_random_uuid()::text, 'APROSS', 'APROSS'),
    (gen_random_uuid()::text, 'OSEP', 'OSEP Mendoza'),
    (gen_random_uuid()::text, 'OSEF', 'OSEF'),
    (gen_random_uuid()::text, 'IOSPER', 'IOSPER'),
    (gen_random_uuid()::text, 'IPROSS', 'IPROSS'),
    (gen_random_uuid()::text, 'ISSN', 'ISSN'),
    (gen_random_uuid()::text, 'IPS', 'Instituto Provincial de Salud de Salta'),
    (gen_random_uuid()::text, 'ISJ', 'Instituto de Seguros de Jujuy'),
    (gen_random_uuid()::text, 'INSSSEP', 'INSSSEP Chaco'),
    (gen_random_uuid()::text, 'IASEP', 'IASEP Formosa'),
    (gen_random_uuid()::text, 'SEROS', 'SEROS Chubut'),
    (gen_random_uuid()::text, 'SEMPRE', 'SEMPRE La Pampa'),
    (gen_random_uuid()::text, 'ObSBA', 'ObSBA'),
    (gen_random_uuid()::text, 'IOSFA', 'IOSFA'),
    (gen_random_uuid()::text, 'OSPJN', 'Obra Social del Poder Judicial de la Nación'),
    (gen_random_uuid()::text, 'DAS', 'Dirección de Ayuda Social del Congreso'),
    (gen_random_uuid()::text, 'DOSUBA', 'DOSUBA'),
    (gen_random_uuid()::text, 'DASPU', 'DASPU'),
    (gen_random_uuid()::text, 'UNION PERSONAL', 'Unión Personal'),
    (gen_random_uuid()::text, 'OSECAC', 'OSECAC'),
    (gen_random_uuid()::text, 'OSPRERA', 'OSPRERA'),
    (gen_random_uuid()::text, 'OSPE', 'OSPE'),
    (gen_random_uuid()::text, 'OSUTHGRA', 'OSUTHGRA'),
    (gen_random_uuid()::text, 'OSPLAD', 'OSPLAD'),
    (gen_random_uuid()::text, 'UOCRA / CONSTRUIR SALUD', 'UOCRA / Construir Salud'),
    (gen_random_uuid()::text, 'OSMATA', 'OSMATA'),
    (gen_random_uuid()::text, 'OSSEG', 'OSSEG'),
    (gen_random_uuid()::text, 'OSFATLYF', 'OSFATLYF'),
    (gen_random_uuid()::text, 'OSFE', 'Obra Social Ferroviaria'),
    (gen_random_uuid()::text, 'OSFYMT', 'Obra Social del Personal de Farmacias'),
    (gen_random_uuid()::text, 'OSPSA / SANIDAD', 'Obra Social del Personal de la Sanidad Argentina'),
    (gen_random_uuid()::text, 'OSPAT', 'Obra Social del Personal del Turf'),
    (gen_random_uuid()::text, 'ADOS ROSARIO', 'ADOS ROSARIO'),
    (gen_random_uuid()::text, 'AMCI', 'AMCI'),
    (gen_random_uuid()::text, 'AMFFA', 'AMFFA'),
    (gen_random_uuid()::text, 'AMPAR', 'AMPAR'),
    (gen_random_uuid()::text, 'AMPES', 'AMPES'),
    (gen_random_uuid()::text, 'AMUKRA', 'AMUKRA'),
    (gen_random_uuid()::text, 'AMUR', 'AMUR'),
    (gen_random_uuid()::text, 'APDIS', 'APDIS'),
    (gen_random_uuid()::text, 'APDJIC', 'APDJIC'),
    (gen_random_uuid()::text, 'APSOT', 'APSOT'),
    (gen_random_uuid()::text, 'ASE', 'ASE'),
    (gen_random_uuid()::text, 'ASSPE', 'ASSPE'),
    (gen_random_uuid()::text, 'DITEM', 'DITEM'),
    (gen_random_uuid()::text, 'FAA', 'FAA'),
    (gen_random_uuid()::text, 'FEDECAMARAS', 'FEDECAMARAS'),
    (gen_random_uuid()::text, 'FRUTOS', 'FRUTOS'),
    (gen_random_uuid()::text, 'JOHNSON', 'JOHNSON'),
    (gen_random_uuid()::text, 'LUIS PASTEUR', 'LUIS PASTEUR'),
    (gen_random_uuid()::text, 'O.S.A.M.O.C', 'O.S.A.M.O.C'),
    (gen_random_uuid()::text, 'O.S.A.P.S.E', 'O.S.A.P.S.E'),
    (gen_random_uuid()::text, 'O.S.PE.COR', 'O.S.PE.COR'),
    (gen_random_uuid()::text, 'O.S.PE.TAX.R', 'O.S.PE.TAX.R'),
    (gen_random_uuid()::text, 'O.S.PERS.A.A.M.S.', 'O.S.PERS.A.A.M.S.'),
    (gen_random_uuid()::text, 'O.S.S.U.R.R.B.A.C', 'O.S.S.U.R.R.B.A.C'),
    (gen_random_uuid()::text, 'O.S.T.A.C.C', 'O.S.T.A.C.C'),
    (gen_random_uuid()::text, 'O.S.T.C.A.R.A.', 'O.S.T.C.A.R.A.'),
    (gen_random_uuid()::text, 'O.S.TAX.B.A', 'O.S.TAX.B.A'),
    (gen_random_uuid()::text, 'OPDEA', 'OPDEA'),
    (gen_random_uuid()::text, 'OPZC', 'OPZC'),
    (gen_random_uuid()::text, 'GEA SA', 'GEA SA'),
    (gen_random_uuid()::text, 'ROI SA', 'ROI SA'),
    (gen_random_uuid()::text, 'OS.PE.PRI', 'OS.PE.PRI'),
    (gen_random_uuid()::text, 'APRES SA', 'APRES SA'),
    (gen_random_uuid()::text, 'OSA AERONAVEGANTES', 'OSA AERONAVEGANTES'),
    (gen_random_uuid()::text, 'OSA ACTORES', 'OSA ACTORES'),
    (gen_random_uuid()::text, 'OSA ACTORES 2', 'OSA ACTORES 2'),
    (gen_random_uuid()::text, 'OSADEF', 'OSADEF'),
    (gen_random_uuid()::text, 'OSADRA', 'OSADRA'),
    (gen_random_uuid()::text, 'OSAF', 'OSAF'),
    (gen_random_uuid()::text, 'OSAGO', 'OSAGO'),
    (gen_random_uuid()::text, 'OSALARA', 'OSALARA'),
    (gen_random_uuid()::text, 'OSAM', 'OSAM'),
    (gen_random_uuid()::text, 'OSAMF', 'OSAMF'),
    (gen_random_uuid()::text, 'OSAMM', 'OSAMM'),
    (gen_random_uuid()::text, 'OSAMMVC', 'OSAMMVC'),
    (gen_random_uuid()::text, 'OSAMP', 'OSAMP'),
    (gen_random_uuid()::text, 'OSAMS', 'OSAMS'),
    (gen_random_uuid()::text, 'OSAOS 1', 'OSAOS 1'),
    (gen_random_uuid()::text, 'OSAOS 2', 'OSAOS 2'),
    (gen_random_uuid()::text, 'OSAOS 3', 'OSAOS 3'),
    (gen_random_uuid()::text, 'OSAP ACEROS PARANA', 'OSAP ACEROS PARANA'),
    (gen_random_uuid()::text, 'OSAPL', 'OSAPL'),
    (gen_random_uuid()::text, 'OSAPM', 'OSAPM'),
    (gen_random_uuid()::text, 'OSAPMCBA', 'OSAPMCBA'),
    (gen_random_uuid()::text, 'OSARP', 'OSARP'),
    (gen_random_uuid()::text, 'ANDESALUD', 'ANDESALUD'),
    (gen_random_uuid()::text, 'AGRUPACION SANATORIAL SUR', 'AGRUPACION SANATORIAL SUR'),
    (gen_random_uuid()::text, 'ASISTENCIA SANITARIA INTEGRAL', 'ASISTENCIA SANITARIA INTEGRAL'),
    (gen_random_uuid()::text, 'ADMINISTRAR SALUD', 'ADMINISTRAR SALUD'),
    (gen_random_uuid()::text, 'ASSISTENCIAL SALUD', 'ASSISTENCIAL SALUD'),
    (gen_random_uuid()::text, 'AMSTERDAM SALUD', 'AMSTERDAM SALUD'),
    (gen_random_uuid()::text, 'OSBA', 'OSBA'),
    (gen_random_uuid()::text, 'OSBARA', 'OSBARA'),
    (gen_random_uuid()::text, 'BIENESTAR SALUD', 'BIENESTAR SALUD'),
    (gen_random_uuid()::text, 'BONMED', 'BONMED'),
    (gen_random_uuid()::text, 'OSCA', 'OSCA'),
    (gen_random_uuid()::text, 'OSCAMGLYP', 'OSCAMGLYP'),
    (gen_random_uuid()::text, 'OSCAPBAQFLU', 'OSCAPBAQFLU'),
    (gen_random_uuid()::text, 'OSCCP', 'OSCCP'),
    (gen_random_uuid()::text, 'OSCE', 'OSCE'),
    (gen_random_uuid()::text, 'OSCEA', 'OSCEA'),
    (gen_random_uuid()::text, 'OSCEP', 'OSCEP'),
    (gen_random_uuid()::text, 'OSCHOCA', 'OSCHOCA'),
    (gen_random_uuid()::text, 'OSCMJ', 'OSCMJ'),
    (gen_random_uuid()::text, 'OSCML', 'OSCML'),
    (gen_random_uuid()::text, 'OSCMM', 'OSCMM'),
    (gen_random_uuid()::text, 'OSCOEMA', 'OSCOEMA'),
    (gen_random_uuid()::text, 'OSCOMM', 'OSCOMM'),
    (gen_random_uuid()::text, 'OSCONARA', 'OSCONARA'),
    (gen_random_uuid()::text, 'OSCRAIA', 'OSCRAIA'),
    (gen_random_uuid()::text, 'CARE SALUD', 'CARE SALUD'),
    (gen_random_uuid()::text, 'CORSAL', 'CORSAL'),
    (gen_random_uuid()::text, 'CYNTHIOS SALUD', 'CYNTHIOS SALUD'),
    (gen_random_uuid()::text, 'OSCTC', 'OSCTC'),
    (gen_random_uuid()::text, 'OSDAA', 'OSDAA'),
    (gen_random_uuid()::text, 'OSDEL', 'OSDEL'),
    (gen_random_uuid()::text, 'OSDEM', 'OSDEM'),
    (gen_random_uuid()::text, 'OSDEPYM', 'OSDEPYM'),
    (gen_random_uuid()::text, 'OSDIC', 'OSDIC'),
    (gen_random_uuid()::text, 'OSDIPP', 'OSDIPP'),
    (gen_random_uuid()::text, 'OSDO', 'OSDO'),
    (gen_random_uuid()::text, 'OSDOP', 'OSDOP'),
    (gen_random_uuid()::text, 'OSEADI', 'OSEADI'),
    (gen_random_uuid()::text, 'OSEAM', 'OSEAM'),
    (gen_random_uuid()::text, 'OSEDA', 'OSEDA'),
    (gen_random_uuid()::text, 'OSEDEIV', 'OSEDEIV'),
    (gen_random_uuid()::text, 'OSEIV', 'OSEIV'),
    (gen_random_uuid()::text, 'OSEMM', 'OSEMM'),
    (gen_random_uuid()::text, 'EMINENTE MEDICINAL', 'EMINENTE MEDICINAL'),
    (gen_random_uuid()::text, 'OSEN', 'OSEN'),
    (gen_random_uuid()::text, 'OSEPC', 'OSEPC'),
    (gen_random_uuid()::text, 'OSEPJ', 'OSEPJ'),
    (gen_random_uuid()::text, 'ENSALUD', 'ENSALUD'),
    (gen_random_uuid()::text, 'OSETRA', 'OSETRA'),
    (gen_random_uuid()::text, 'OSETYA', 'OSETYA'),
    (gen_random_uuid()::text, 'OSFAS', 'OSFAS'),
    (gen_random_uuid()::text, 'OSFATUN', 'OSFATUN'),
    (gen_random_uuid()::text, 'OSFFENTOS', 'OSFFENTOS'),
    (gen_random_uuid()::text, 'OSFGP', 'OSFGP'),
    (gen_random_uuid()::text, 'OSFOT', 'OSFOT'),
    (gen_random_uuid()::text, 'OSFYB', 'OSFYB'),
    (gen_random_uuid()::text, 'OSFYHC', 'OSFYHC'),
    (gen_random_uuid()::text, 'OSGMG', 'OSGMG'),
    (gen_random_uuid()::text, 'GRUPO MEDICO INCAS', 'GRUPO MEDICO INCAS'),
    (gen_random_uuid()::text, 'GERMED', 'GERMED'),
    (gen_random_uuid()::text, 'GILSA', 'GILSA'),
    (gen_random_uuid()::text, 'GRUPO DDM', 'GRUPO DDM'),
    (gen_random_uuid()::text, 'HOSPITAL ALEMAN RNAS', 'HOSPITAL ALEMAN RNAS'),
    (gen_random_uuid()::text, 'HOSPITAL BRITANICO', 'HOSPITAL BRITANICO'),
    (gen_random_uuid()::text, 'OSIAD', 'OSIAD'),
    (gen_random_uuid()::text, 'OSIM', 'OSIM'),
    (gen_random_uuid()::text, 'OSIPA', 'OSIPA'),
    (gen_random_uuid()::text, 'OSITAC', 'OSITAC'),
    (gen_random_uuid()::text, 'OSLYF', 'OSLYF'),
    (gen_random_uuid()::text, 'OSLYF PATAGONIA', 'OSLYF PATAGONIA'),
    (gen_random_uuid()::text, 'MET-CORDOBA', 'MET-CORDOBA'),
    (gen_random_uuid()::text, 'OSMA', 'OSMA'),
    (gen_random_uuid()::text, 'OSMAD', 'OSMAD'),
    (gen_random_uuid()::text, 'MEDYCIN ARGENTINO', 'MEDYCIN ARGENTINO'),
    (gen_random_uuid()::text, 'OSME', 'OSME'),
    (gen_random_uuid()::text, 'OSMEDICA', 'OSMEDICA'),
    (gen_random_uuid()::text, 'OSMISS', 'OSMISS'),
    (gen_random_uuid()::text, 'OSMITA', 'OSMITA'),
    (gen_random_uuid()::text, 'MUTUAL MEDICA CONCORDIA', 'MUTUAL MEDICA CONCORDIA'),
    (gen_random_uuid()::text, 'OSMMEDT', 'OSMMEDT'),
    (gen_random_uuid()::text, 'OSMPA', 'OSMPA'),
    (gen_random_uuid()::text, 'OSMPC', 'OSMPC'),
    (gen_random_uuid()::text, 'MEDICINA PRIVADA SRL', 'MEDICINA PRIVADA SRL'),
    (gen_random_uuid()::text, 'MEMED', 'MEMED'),
    (gen_random_uuid()::text, 'MEDICAL SERVICIOS DE SALUD', 'MEDICAL SERVICIOS DE SALUD'),
    (gen_random_uuid()::text, 'OSMTT', 'OSMTT'),
    (gen_random_uuid()::text, 'NOBIS', 'NOBIS'),
    (gen_random_uuid()::text, 'OSOC', 'OSOC'),
    (gen_random_uuid()::text, 'OSOCNA', 'OSOCNA'),
    (gen_random_uuid()::text, 'OSOEF', 'OSOEF'),
    (gen_random_uuid()::text, 'OSOETSYLARA', 'OSOETSYLARA'),
    (gen_random_uuid()::text, 'OSOPP', 'OSOPP'),
    (gen_random_uuid()::text, 'OSOSS', 'OSOSS'),
    (gen_random_uuid()::text, 'PLENIMEDICAL', 'PLENIMEDICAL'),
    (gen_random_uuid()::text, 'OSPA PORTUARIOS', 'OSPA PORTUARIOS'),
    (gen_random_uuid()::text, 'OSPA AERONAUTICO', 'OSPA AERONAUTICO'),
    (gen_random_uuid()::text, 'OSPA AZUCAR 1', 'OSPA AZUCAR 1'),
    (gen_random_uuid()::text, 'OSPA AZUCAR 2', 'OSPA AZUCAR 2'),
    (gen_random_uuid()::text, 'OSPA PORTUARIOS 2', 'OSPA PORTUARIOS 2'),
    (gen_random_uuid()::text, 'OSPA-VIAL', 'OSPA-VIAL'),
    (gen_random_uuid()::text, 'OSPAA', 'OSPAA'),
    (gen_random_uuid()::text, 'OSPACA 1', 'OSPACA 1'),
    (gen_random_uuid()::text, 'OSPACA 2', 'OSPACA 2'),
    (gen_random_uuid()::text, 'OSPACP', 'OSPACP'),
    (gen_random_uuid()::text, 'OSPADEP', 'OSPADEP'),
    (gen_random_uuid()::text, 'OSPAF', 'OSPAF'),
    (gen_random_uuid()::text, 'OSPAGA', 'OSPAGA'),
    (gen_random_uuid()::text, 'OSPAIL', 'OSPAIL'),
    (gen_random_uuid()::text, 'OSPAÑA', 'OSPAÑA'),
    (gen_random_uuid()::text, 'OSPAP', 'OSPAP'),
    (gen_random_uuid()::text, 'OSPATCA', 'OSPATCA'),
    (gen_random_uuid()::text, 'OSPAV', 'OSPAV'),
    (gen_random_uuid()::text, 'OSPBL', 'OSPBL'),
    (gen_random_uuid()::text, 'OSPCR', 'OSPCR'),
    (gen_random_uuid()::text, 'OSPCRA', 'OSPCRA'),
    (gen_random_uuid()::text, 'OSPCSPMYA', 'OSPCSPMYA'),
    (gen_random_uuid()::text, 'OSPCYD', 'OSPCYD'),
    (gen_random_uuid()::text, 'OSPDESBA', 'OSPDESBA'),
    (gen_random_uuid()::text, 'OSPDI', 'OSPDI'),
    (gen_random_uuid()::text, 'OSPE 1', 'OSPE 1'),
    (gen_random_uuid()::text, 'OSPE ESCRIBANOS', 'OSPE ESCRIBANOS'),
    (gen_random_uuid()::text, 'OSPEA', 'OSPEA'),
    (gen_random_uuid()::text, 'OSPEC', 'OSPEC'),
    (gen_random_uuid()::text, 'OSPECA', 'OSPECA'),
    (gen_random_uuid()::text, 'OSPEDICI', 'OSPEDICI'),
    (gen_random_uuid()::text, 'OSPEDYB', 'OSPEDYB'),
    (gen_random_uuid()::text, 'OSPEDYC', 'OSPEDYC'),
    (gen_random_uuid()::text, 'OSPEF Y EPCA', 'OSPEF Y EPCA'),
    (gen_random_uuid()::text, 'OSPEJ', 'OSPEJ'),
    (gen_random_uuid()::text, 'OSPEL', 'OSPEL'),
    (gen_random_uuid()::text, 'OSPEMER', 'OSPEMER'),
    (gen_random_uuid()::text, 'OSPEMOM', 'OSPEMOM'),
    (gen_random_uuid()::text, 'OSPENA', 'OSPENA'),
    (gen_random_uuid()::text, 'OSPEP 1', 'OSPEP 1'),
    (gen_random_uuid()::text, 'OSPEP 2', 'OSPEP 2'),
    (gen_random_uuid()::text, 'OSPEP 3', 'OSPEP 3'),
    (gen_random_uuid()::text, 'OSPEP DIRECCION', 'OSPEP DIRECCION'),
    (gen_random_uuid()::text, 'OSPEPBA', 'OSPEPBA'),
    (gen_random_uuid()::text, 'OSPEPRI / MEOPP', 'OSPEPRI / MEOPP'),
    (gen_random_uuid()::text, 'OSPERCIN', 'OSPERCIN'),
    (gen_random_uuid()::text, 'OSPERYH', 'OSPERYH'),
    (gen_random_uuid()::text, 'OSPERYHRA', 'OSPERYHRA'),
    (gen_random_uuid()::text, 'OSPES', 'OSPES'),
    (gen_random_uuid()::text, 'OSPESA', 'OSPESA'),
    (gen_random_uuid()::text, 'OSPESCA', 'OSPESCA'),
    (gen_random_uuid()::text, 'OSPESCHA', 'OSPESCHA'),
    (gen_random_uuid()::text, 'OSPESGA', 'OSPESGA'),
    (gen_random_uuid()::text, 'OSPESGYPE', 'OSPESGYPE'),
    (gen_random_uuid()::text, 'OSPETAX', 'OSPETAX'),
    (gen_random_uuid()::text, 'OSPETELCO', 'OSPETELCO'),
    (gen_random_uuid()::text, 'OSPEVIC', 'OSPEVIC'),
    (gen_random_uuid()::text, 'OSPFS', 'OSPFS'),
    (gen_random_uuid()::text, 'OSPG', 'OSPG'),
    (gen_random_uuid()::text, 'OSPHGBAYSI', 'OSPHGBAYSI'),
    (gen_random_uuid()::text, 'OSPIA 1', 'OSPIA 1'),
    (gen_random_uuid()::text, 'OSPIA 2', 'OSPIA 2'),
    (gen_random_uuid()::text, 'OSPIC 1', 'OSPIC 1'),
    (gen_random_uuid()::text, 'OSPIC 2', 'OSPIC 2'),
    (gen_random_uuid()::text, 'OSPIC SANTA FE', 'OSPIC SANTA FE'),
    (gen_random_uuid()::text, 'OSPICA', 'OSPICA'),
    (gen_random_uuid()::text, 'OSPICAL', 'OSPICAL'),
    (gen_random_uuid()::text, 'OSPICHA', 'OSPICHA'),
    (gen_random_uuid()::text, 'OSPIDA', 'OSPIDA'),
    (gen_random_uuid()::text, 'OSPIF 1', 'OSPIF 1'),
    (gen_random_uuid()::text, 'OSPIF 2', 'OSPIF 2'),
    (gen_random_uuid()::text, 'OSPIFSE', 'OSPIFSE'),
    (gen_random_uuid()::text, 'OSPIG', 'OSPIG'),
    (gen_random_uuid()::text, 'OSPIHMP', 'OSPIHMP'),
    (gen_random_uuid()::text, 'OSPIL', 'OSPIL'),
    (gen_random_uuid()::text, 'OSPILM', 'OSPILM'),
    (gen_random_uuid()::text, 'OSPIM 1', 'OSPIM 1'),
    (gen_random_uuid()::text, 'OSPIM 2', 'OSPIM 2'),
    (gen_random_uuid()::text, 'OSPIN 1', 'OSPIN 1'),
    (gen_random_uuid()::text, 'OSPIN 2', 'OSPIN 2'),
    (gen_random_uuid()::text, 'OSPIP 1', 'OSPIP 1'),
    (gen_random_uuid()::text, 'OSPIP 2', 'OSPIP 2'),
    (gen_random_uuid()::text, 'OSPIP 3', 'OSPIP 3'),
    (gen_random_uuid()::text, 'OSPIQYP', 'OSPIQYP'),
    (gen_random_uuid()::text, 'OSPIS', 'OSPIS'),
    (gen_random_uuid()::text, 'OSPIT 1', 'OSPIT 1'),
    (gen_random_uuid()::text, 'OSPIT 2', 'OSPIT 2'),
    (gen_random_uuid()::text, 'OSPIT 3', 'OSPIT 3'),
    (gen_random_uuid()::text, 'OSPIV 1', 'OSPIV 1'),
    (gen_random_uuid()::text, 'OSPIV 2', 'OSPIV 2'),
    (gen_random_uuid()::text, 'OSPJC', 'OSPJC'),
    (gen_random_uuid()::text, 'OSPJT', 'OSPJT'),
    (gen_random_uuid()::text, 'OSPL', 'OSPL'),
    (gen_random_uuid()::text, 'OSPLA', 'OSPLA'),
    (gen_random_uuid()::text, 'OSPM 1', 'OSPM 1'),
    (gen_random_uuid()::text, 'OSPM 2', 'OSPM 2'),
    (gen_random_uuid()::text, 'OSPM 3', 'OSPM 3'),
    (gen_random_uuid()::text, 'OSPMA', 'OSPMA'),
    (gen_random_uuid()::text, 'OSPMJ', 'OSPMJ'),
    (gen_random_uuid()::text, 'OSPMM', 'OSPMM'),
    (gen_random_uuid()::text, 'OSPMS', 'OSPMS'),
    (gen_random_uuid()::text, 'OSPMT', 'OSPMT'),
    (gen_random_uuid()::text, 'OSPOCE', 'OSPOCE'),
    (gen_random_uuid()::text, 'OSPP', 'OSPP'),
    (gen_random_uuid()::text, 'OSPPB 1', 'OSPPB 1'),
    (gen_random_uuid()::text, 'OSPPB 2', 'OSPPB 2'),
    (gen_random_uuid()::text, 'OSPPCYQ', 'OSPPCYQ'),
    (gen_random_uuid()::text, 'OSPPEA', 'OSPPEA'),
    (gen_random_uuid()::text, 'OSPPM PRENSA', 'OSPPM PRENSA'),
    (gen_random_uuid()::text, 'OSPPM PUERTOS', 'OSPPM PUERTOS'),
    (gen_random_uuid()::text, 'OSPPRA', 'OSPPRA'),
    (gen_random_uuid()::text, 'OSPRB', 'OSPRB'),
    (gen_random_uuid()::text, 'OSPREME', 'OSPREME'),
    (gen_random_uuid()::text, 'OSPREN', 'OSPREN'),
    (gen_random_uuid()::text, 'OSPRENTUC', 'OSPRENTUC'),
    (gen_random_uuid()::text, 'OSPRM', 'OSPRM'),
    (gen_random_uuid()::text, 'OSPRO', 'OSPRO'),
    (gen_random_uuid()::text, 'OSPROTURA', 'OSPROTURA'),
    (gen_random_uuid()::text, 'OSPS PREVENCION', 'OSPS PREVENCION'),
    (gen_random_uuid()::text, 'PARQUE SALUD', 'PARQUE SALUD'),
    (gen_random_uuid()::text, 'PREMEDICA', 'PREMEDICA'),
    (gen_random_uuid()::text, 'PRESTADORES SANATORIALES', 'PRESTADORES SANATORIALES'),
    (gen_random_uuid()::text, 'PRIMED', 'PRIMED'),
    (gen_random_uuid()::text, 'PRIVAMED', 'PRIVAMED'),
    (gen_random_uuid()::text, 'OSPS MERCEDES', 'OSPS MERCEDES'),
    (gen_random_uuid()::text, 'OSPSESBA', 'OSPSESBA'),
    (gen_random_uuid()::text, 'OSPSIP', 'OSPSIP'),
    (gen_random_uuid()::text, 'OSPTA', 'OSPTA'),
    (gen_random_uuid()::text, 'OSPTV', 'OSPTV'),
    (gen_random_uuid()::text, 'OSPUAYE', 'OSPUAYE'),
    (gen_random_uuid()::text, 'OSRGA', 'OSRGA'),
    (gen_random_uuid()::text, 'OSRJA', 'OSRJA'),
    (gen_random_uuid()::text, 'OSRM', 'OSRM'),
    (gen_random_uuid()::text, 'MC SALUD', 'MC SALUD'),
    (gen_random_uuid()::text, 'SUPERCO', 'SUPERCO'),
    (gen_random_uuid()::text, 'SOREMER', 'SOREMER'),
    (gen_random_uuid()::text, 'OSSA', 'OSSA'),
    (gen_random_uuid()::text, 'OSSACRA', 'OSSACRA'),
    (gen_random_uuid()::text, 'OSSB', 'OSSB'),
    (gen_random_uuid()::text, 'SANTA CLARA', 'SANTA CLARA'),
    (gen_random_uuid()::text, 'SOCIEDAD ITALIANA DE BENEFICENCIA', 'SOCIEDAD ITALIANA DE BENEFICENCIA'),
    (gen_random_uuid()::text, 'OSSIMRA', 'OSSIMRA'),
    (gen_random_uuid()::text, 'OSSOELSAC', 'OSSOELSAC'),
    (gen_random_uuid()::text, 'OSSPYFER', 'OSSPYFER'),
    (gen_random_uuid()::text, 'SABER SA', 'SABER SA'),
    (gen_random_uuid()::text, 'SAJU SRL', 'SAJU SRL'),
    (gen_random_uuid()::text, 'SCIS SA', 'SCIS SA'),
    (gen_random_uuid()::text, 'OSTAD', 'OSTAD'),
    (gen_random_uuid()::text, 'OSTAMMA', 'OSTAMMA'),
    (gen_random_uuid()::text, 'OSTC', 'OSTC'),
    (gen_random_uuid()::text, 'OSTECF', 'OSTECF'),
    (gen_random_uuid()::text, 'OSTEE', 'OSTEE'),
    (gen_random_uuid()::text, 'OSTEL', 'OSTEL'),
    (gen_random_uuid()::text, 'OSTEP', 'OSTEP'),
    (gen_random_uuid()::text, 'OSTES', 'OSTES'),
    (gen_random_uuid()::text, 'OSTIG', 'OSTIG'),
    (gen_random_uuid()::text, 'OSTP', 'OSTP'),
    (gen_random_uuid()::text, 'OSTPBA', 'OSTPBA'),
    (gen_random_uuid()::text, 'OSTPCHPYARA', 'OSTPCHPYARA'),
    (gen_random_uuid()::text, 'OSTRAC', 'OSTRAC'),
    (gen_random_uuid()::text, 'OSTSA', 'OSTSA'),
    (gen_random_uuid()::text, 'OSTVA', 'OSTVA'),
    (gen_random_uuid()::text, 'OSTVENDRA', 'OSTVENDRA'),
    (gen_random_uuid()::text, 'OSTVLA', 'OSTVLA'),
    (gen_random_uuid()::text, 'OSUCI', 'OSUCI'),
    (gen_random_uuid()::text, 'OSUOMRA', 'OSUOMRA'),
    (gen_random_uuid()::text, 'OSUTI', 'OSUTI'),
    (gen_random_uuid()::text, 'OSV', 'OSV'),
    (gen_random_uuid()::text, 'OSVARA', 'OSVARA'),
    (gen_random_uuid()::text, 'OSVAS', 'OSVAS'),
    (gen_random_uuid()::text, 'VITAS SA', 'VITAS SA'),
    (gen_random_uuid()::text, 'OSVVRA / ANDAR', 'OSVVRA / ANDAR'),
    (gen_random_uuid()::text, 'OSYC', 'OSYC'),
    (gen_random_uuid()::text, 'OSYPF', 'OSYPF'),
    (gen_random_uuid()::text, 'SANOS / NATIVUS', 'SANOS / NATIVUS'),
    (gen_random_uuid()::text, 'SERVESALUD', 'SERVESALUD'),
    (gen_random_uuid()::text, 'SALUD PROFESIONAL Y TECNOLOGICA', 'SALUD PROFESIONAL Y TECNOLOGICA'),
    (gen_random_uuid()::text, 'UPFPARA', 'UPFPARA'),
    (gen_random_uuid()::text, 'WHOPE', 'WHOPE')
ON CONFLICT ("nombre") DO NOTHING;
