-- AlterTable
ALTER TABLE "Prepaga" ADD COLUMN "nombreCompleto" TEXT;

-- Seed: columna "Nombre" de semio360_obras_sociales_prepagas_argentina.xlsx (se cruza por "Sigla / Alias")
UPDATE "Prepaga" p SET "nombreCompleto" = v.nombre_completo
FROM (VALUES
    ('PARTICULAR', 'Particular / Consulta Privada'),
    ('ACCORD SALUD', 'Accord Salud'),
    ('AVALIAN', 'Avalian Cobertura Médica Integral (ex ACA Salud)'),
    ('BOREAL', 'Boreal Cobertura de Salud'),
    ('BRISTOL', 'Bristol Medicine'),
    ('CEMIC', 'CEMIC'),
    ('EMERGENCIAS', 'Emergencias Salud'),
    ('ESENCIAL', 'Medicina Esencial'),
    ('FEDERADA SALUD', 'Federada Salud'),
    ('GALENO', 'Galeno Argentina'),
    ('HOMINIS', 'Medicina Prepaga Hominis'),
    ('HOSPITAL ALEMAN', 'Hospital Alemán'),
    ('HOSPITAL AUSTRAL', 'Hospital Austral'),
    ('JERARQUICOS SALUD', 'Jerárquicos Salud'),
    ('MEDICUS', 'Medicus Medicina Prepaga'),
    ('MEDIFE', 'Medifé Asociación Civil'),
    ('OMINT', 'OMINT'),
    ('OSDE', 'OSDE Binario'),
    ('PREVENCION', 'Prevención Salud'),
    ('SANCOR', 'SanCor Salud'),
    ('SMG', 'Swiss Medical Medicina Privada'),
    ('SIPSSA', 'SIPSSA Medicina Prepaga'),
    ('PAMI / INSSJP', 'PAMI / INSSJP'),
    ('IOMA', 'IOMA'),
    ('IAPOS', 'IAPOS'),
    ('IOSCOR', 'IOSCOR'),
    ('APROSS', 'APROSS'),
    ('OSEP', 'OSEP Mendoza'),
    ('OSEF', 'OSEF'),
    ('IOSPER', 'IOSPER'),
    ('IPROSS', 'IPROSS'),
    ('ISSN', 'ISSN'),
    ('IPS', 'Instituto Provincial de Salud de Salta'),
    ('ISJ', 'Instituto de Seguros de Jujuy'),
    ('INSSSEP', 'INSSSEP Chaco'),
    ('IASEP', 'IASEP Formosa'),
    ('SEROS', 'SEROS Chubut'),
    ('SEMPRE', 'SEMPRE La Pampa'),
    ('ObSBA', 'ObSBA'),
    ('IOSFA', 'IOSFA'),
    ('OSPJN', 'Obra Social del Poder Judicial de la Nación'),
    ('DAS', 'Dirección de Ayuda Social del Congreso'),
    ('DOSUBA', 'DOSUBA'),
    ('DASPU', 'DASPU'),
    ('UNION PERSONAL', 'Unión Personal'),
    ('OSECAC', 'OSECAC'),
    ('OSPRERA', 'OSPRERA'),
    ('OSPE', 'OSPE'),
    ('OSUTHGRA', 'OSUTHGRA'),
    ('OSPLAD', 'OSPLAD'),
    ('UOCRA / CONSTRUIR SALUD', 'UOCRA / Construir Salud'),
    ('OSMATA', 'OSMATA'),
    ('OSSEG', 'OSSEG'),
    ('OSFATLYF', 'OSFATLYF'),
    ('OSFE', 'Obra Social Ferroviaria'),
    ('OSFYMT', 'Obra Social del Personal de Farmacias'),
    ('OSPSA / SANIDAD', 'Obra Social del Personal de la Sanidad Argentina'),
    ('OSPAT', 'Obra Social del Personal del Turf'),
    ('ADOS ROSARIO', 'ADOS ROSARIO'),
    ('AMCI', 'AMCI'),
    ('AMFFA', 'AMFFA'),
    ('AMPAR', 'AMPAR'),
    ('AMPES', 'AMPES'),
    ('AMUKRA', 'AMUKRA'),
    ('AMUR', 'AMUR'),
    ('APDIS', 'APDIS'),
    ('APDJIC', 'APDJIC'),
    ('APSOT', 'APSOT'),
    ('ASE', 'ASE'),
    ('ASSPE', 'ASSPE'),
    ('DITEM', 'DITEM'),
    ('FAA', 'FAA'),
    ('FEDECAMARAS', 'FEDECAMARAS'),
    ('FRUTOS', 'FRUTOS'),
    ('JOHNSON', 'JOHNSON'),
    ('LUIS PASTEUR', 'LUIS PASTEUR'),
    ('O.S.A.M.O.C', 'O.S.A.M.O.C'),
    ('O.S.A.P.S.E', 'O.S.A.P.S.E'),
    ('O.S.PE.COR', 'O.S.PE.COR'),
    ('O.S.PE.TAX.R', 'O.S.PE.TAX.R'),
    ('O.S.PERS.A.A.M.S.', 'O.S.PERS.A.A.M.S.'),
    ('O.S.S.U.R.R.B.A.C', 'O.S.S.U.R.R.B.A.C'),
    ('O.S.T.A.C.C', 'O.S.T.A.C.C'),
    ('O.S.T.C.A.R.A.', 'O.S.T.C.A.R.A.'),
    ('O.S.TAX.B.A', 'O.S.TAX.B.A'),
    ('OPDEA', 'OPDEA'),
    ('OPZC', 'OPZC'),
    ('GEA SA', 'GEA SA'),
    ('ROI SA', 'ROI SA'),
    ('OS.PE.PRI', 'OS.PE.PRI'),
    ('APRES SA', 'APRES SA'),
    ('OSA AERONAVEGANTES', 'OSA AERONAVEGANTES'),
    ('OSA ACTORES', 'OSA ACTORES'),
    ('OSA ACTORES 2', 'OSA ACTORES 2'),
    ('OSADEF', 'OSADEF'),
    ('OSADRA', 'OSADRA'),
    ('OSAF', 'OSAF'),
    ('OSAGO', 'OSAGO'),
    ('OSALARA', 'OSALARA'),
    ('OSAM', 'OSAM'),
    ('OSAMF', 'OSAMF'),
    ('OSAMM', 'OSAMM'),
    ('OSAMMVC', 'OSAMMVC'),
    ('OSAMP', 'OSAMP'),
    ('OSAMS', 'OSAMS'),
    ('OSAOS 1', 'OSAOS 1'),
    ('OSAOS 2', 'OSAOS 2'),
    ('OSAOS 3', 'OSAOS 3'),
    ('OSAP ACEROS PARANA', 'OSAP ACEROS PARANA'),
    ('OSAPL', 'OSAPL'),
    ('OSAPM', 'OSAPM'),
    ('OSAPMCBA', 'OSAPMCBA'),
    ('OSARP', 'OSARP'),
    ('ANDESALUD', 'ANDESALUD'),
    ('AGRUPACION SANATORIAL SUR', 'AGRUPACION SANATORIAL SUR'),
    ('ASISTENCIA SANITARIA INTEGRAL', 'ASISTENCIA SANITARIA INTEGRAL'),
    ('ADMINISTRAR SALUD', 'ADMINISTRAR SALUD'),
    ('ASSISTENCIAL SALUD', 'ASSISTENCIAL SALUD'),
    ('AMSTERDAM SALUD', 'AMSTERDAM SALUD'),
    ('OSBA', 'OSBA'),
    ('OSBARA', 'OSBARA'),
    ('BIENESTAR SALUD', 'BIENESTAR SALUD'),
    ('BONMED', 'BONMED'),
    ('OSCA', 'OSCA'),
    ('OSCAMGLYP', 'OSCAMGLYP'),
    ('OSCAPBAQFLU', 'OSCAPBAQFLU'),
    ('OSCCP', 'OSCCP'),
    ('OSCE', 'OSCE'),
    ('OSCEA', 'OSCEA'),
    ('OSCEP', 'OSCEP'),
    ('OSCHOCA', 'OSCHOCA'),
    ('OSCMJ', 'OSCMJ'),
    ('OSCML', 'OSCML'),
    ('OSCMM', 'OSCMM'),
    ('OSCOEMA', 'OSCOEMA'),
    ('OSCOMM', 'OSCOMM'),
    ('OSCONARA', 'OSCONARA'),
    ('OSCRAIA', 'OSCRAIA'),
    ('CARE SALUD', 'CARE SALUD'),
    ('CORSAL', 'CORSAL'),
    ('CYNTHIOS SALUD', 'CYNTHIOS SALUD'),
    ('OSCTC', 'OSCTC'),
    ('OSDAA', 'OSDAA'),
    ('OSDEL', 'OSDEL'),
    ('OSDEM', 'OSDEM'),
    ('OSDEPYM', 'OSDEPYM'),
    ('OSDIC', 'OSDIC'),
    ('OSDIPP', 'OSDIPP'),
    ('OSDO', 'OSDO'),
    ('OSDOP', 'OSDOP'),
    ('OSEADI', 'OSEADI'),
    ('OSEAM', 'OSEAM'),
    ('OSEDA', 'OSEDA'),
    ('OSEDEIV', 'OSEDEIV'),
    ('OSEIV', 'OSEIV'),
    ('OSEMM', 'OSEMM'),
    ('EMINENTE MEDICINAL', 'EMINENTE MEDICINAL'),
    ('OSEN', 'OSEN'),
    ('OSEPC', 'OSEPC'),
    ('OSEPJ', 'OSEPJ'),
    ('ENSALUD', 'ENSALUD'),
    ('OSETRA', 'OSETRA'),
    ('OSETYA', 'OSETYA'),
    ('OSFAS', 'OSFAS'),
    ('OSFATUN', 'OSFATUN'),
    ('OSFFENTOS', 'OSFFENTOS'),
    ('OSFGP', 'OSFGP'),
    ('OSFOT', 'OSFOT'),
    ('OSFYB', 'OSFYB'),
    ('OSFYHC', 'OSFYHC'),
    ('OSGMG', 'OSGMG'),
    ('GRUPO MEDICO INCAS', 'GRUPO MEDICO INCAS'),
    ('GERMED', 'GERMED'),
    ('GILSA', 'GILSA'),
    ('GRUPO DDM', 'GRUPO DDM'),
    ('HOSPITAL ALEMAN RNAS', 'HOSPITAL ALEMAN RNAS'),
    ('HOSPITAL BRITANICO', 'HOSPITAL BRITANICO'),
    ('OSIAD', 'OSIAD'),
    ('OSIM', 'OSIM'),
    ('OSIPA', 'OSIPA'),
    ('OSITAC', 'OSITAC'),
    ('OSLYF', 'OSLYF'),
    ('OSLYF PATAGONIA', 'OSLYF PATAGONIA'),
    ('MET-CORDOBA', 'MET-CORDOBA'),
    ('OSMA', 'OSMA'),
    ('OSMAD', 'OSMAD'),
    ('MEDYCIN ARGENTINO', 'MEDYCIN ARGENTINO'),
    ('OSME', 'OSME'),
    ('OSMEDICA', 'OSMEDICA'),
    ('OSMISS', 'OSMISS'),
    ('OSMITA', 'OSMITA'),
    ('MUTUAL MEDICA CONCORDIA', 'MUTUAL MEDICA CONCORDIA'),
    ('OSMMEDT', 'OSMMEDT'),
    ('OSMPA', 'OSMPA'),
    ('OSMPC', 'OSMPC'),
    ('MEDICINA PRIVADA SRL', 'MEDICINA PRIVADA SRL'),
    ('MEMED', 'MEMED'),
    ('MEDICAL SERVICIOS DE SALUD', 'MEDICAL SERVICIOS DE SALUD'),
    ('OSMTT', 'OSMTT'),
    ('NOBIS', 'NOBIS'),
    ('OSOC', 'OSOC'),
    ('OSOCNA', 'OSOCNA'),
    ('OSOEF', 'OSOEF'),
    ('OSOETSYLARA', 'OSOETSYLARA'),
    ('OSOPP', 'OSOPP'),
    ('OSOSS', 'OSOSS'),
    ('PLENIMEDICAL', 'PLENIMEDICAL'),
    ('OSPA PORTUARIOS', 'OSPA PORTUARIOS'),
    ('OSPA AERONAUTICO', 'OSPA AERONAUTICO'),
    ('OSPA AZUCAR 1', 'OSPA AZUCAR 1'),
    ('OSPA AZUCAR 2', 'OSPA AZUCAR 2'),
    ('OSPA PORTUARIOS 2', 'OSPA PORTUARIOS 2'),
    ('OSPA-VIAL', 'OSPA-VIAL'),
    ('OSPAA', 'OSPAA'),
    ('OSPACA 1', 'OSPACA 1'),
    ('OSPACA 2', 'OSPACA 2'),
    ('OSPACP', 'OSPACP'),
    ('OSPADEP', 'OSPADEP'),
    ('OSPAF', 'OSPAF'),
    ('OSPAGA', 'OSPAGA'),
    ('OSPAIL', 'OSPAIL'),
    ('OSPAÑA', 'OSPAÑA'),
    ('OSPAP', 'OSPAP'),
    ('OSPATCA', 'OSPATCA'),
    ('OSPAV', 'OSPAV'),
    ('OSPBL', 'OSPBL'),
    ('OSPCR', 'OSPCR'),
    ('OSPCRA', 'OSPCRA'),
    ('OSPCSPMYA', 'OSPCSPMYA'),
    ('OSPCYD', 'OSPCYD'),
    ('OSPDESBA', 'OSPDESBA'),
    ('OSPDI', 'OSPDI'),
    ('OSPE 1', 'OSPE 1'),
    ('OSPE ESCRIBANOS', 'OSPE ESCRIBANOS'),
    ('OSPEA', 'OSPEA'),
    ('OSPEC', 'OSPEC'),
    ('OSPECA', 'OSPECA'),
    ('OSPEDICI', 'OSPEDICI'),
    ('OSPEDYB', 'OSPEDYB'),
    ('OSPEDYC', 'OSPEDYC'),
    ('OSPEF Y EPCA', 'OSPEF Y EPCA'),
    ('OSPEJ', 'OSPEJ'),
    ('OSPEL', 'OSPEL'),
    ('OSPEMER', 'OSPEMER'),
    ('OSPEMOM', 'OSPEMOM'),
    ('OSPENA', 'OSPENA'),
    ('OSPEP 1', 'OSPEP 1'),
    ('OSPEP 2', 'OSPEP 2'),
    ('OSPEP 3', 'OSPEP 3'),
    ('OSPEP DIRECCION', 'OSPEP DIRECCION'),
    ('OSPEPBA', 'OSPEPBA'),
    ('OSPEPRI / MEOPP', 'OSPEPRI / MEOPP'),
    ('OSPERCIN', 'OSPERCIN'),
    ('OSPERYH', 'OSPERYH'),
    ('OSPERYHRA', 'OSPERYHRA'),
    ('OSPES', 'OSPES'),
    ('OSPESA', 'OSPESA'),
    ('OSPESCA', 'OSPESCA'),
    ('OSPESCHA', 'OSPESCHA'),
    ('OSPESGA', 'OSPESGA'),
    ('OSPESGYPE', 'OSPESGYPE'),
    ('OSPETAX', 'OSPETAX'),
    ('OSPETELCO', 'OSPETELCO'),
    ('OSPEVIC', 'OSPEVIC'),
    ('OSPFS', 'OSPFS'),
    ('OSPG', 'OSPG'),
    ('OSPHGBAYSI', 'OSPHGBAYSI'),
    ('OSPIA 1', 'OSPIA 1'),
    ('OSPIA 2', 'OSPIA 2'),
    ('OSPIC 1', 'OSPIC 1'),
    ('OSPIC 2', 'OSPIC 2'),
    ('OSPIC SANTA FE', 'OSPIC SANTA FE'),
    ('OSPICA', 'OSPICA'),
    ('OSPICAL', 'OSPICAL'),
    ('OSPICHA', 'OSPICHA'),
    ('OSPIDA', 'OSPIDA'),
    ('OSPIF 1', 'OSPIF 1'),
    ('OSPIF 2', 'OSPIF 2'),
    ('OSPIFSE', 'OSPIFSE'),
    ('OSPIG', 'OSPIG'),
    ('OSPIHMP', 'OSPIHMP'),
    ('OSPIL', 'OSPIL'),
    ('OSPILM', 'OSPILM'),
    ('OSPIM 1', 'OSPIM 1'),
    ('OSPIM 2', 'OSPIM 2'),
    ('OSPIN 1', 'OSPIN 1'),
    ('OSPIN 2', 'OSPIN 2'),
    ('OSPIP 1', 'OSPIP 1'),
    ('OSPIP 2', 'OSPIP 2'),
    ('OSPIP 3', 'OSPIP 3'),
    ('OSPIQYP', 'OSPIQYP'),
    ('OSPIS', 'OSPIS'),
    ('OSPIT 1', 'OSPIT 1'),
    ('OSPIT 2', 'OSPIT 2'),
    ('OSPIT 3', 'OSPIT 3'),
    ('OSPIV 1', 'OSPIV 1'),
    ('OSPIV 2', 'OSPIV 2'),
    ('OSPJC', 'OSPJC'),
    ('OSPJT', 'OSPJT'),
    ('OSPL', 'OSPL'),
    ('OSPLA', 'OSPLA'),
    ('OSPM 1', 'OSPM 1'),
    ('OSPM 2', 'OSPM 2'),
    ('OSPM 3', 'OSPM 3'),
    ('OSPMA', 'OSPMA'),
    ('OSPMJ', 'OSPMJ'),
    ('OSPMM', 'OSPMM'),
    ('OSPMS', 'OSPMS'),
    ('OSPMT', 'OSPMT'),
    ('OSPOCE', 'OSPOCE'),
    ('OSPP', 'OSPP'),
    ('OSPPB 1', 'OSPPB 1'),
    ('OSPPB 2', 'OSPPB 2'),
    ('OSPPCYQ', 'OSPPCYQ'),
    ('OSPPEA', 'OSPPEA'),
    ('OSPPM PRENSA', 'OSPPM PRENSA'),
    ('OSPPM PUERTOS', 'OSPPM PUERTOS'),
    ('OSPPRA', 'OSPPRA'),
    ('OSPRB', 'OSPRB'),
    ('OSPREME', 'OSPREME'),
    ('OSPREN', 'OSPREN'),
    ('OSPRENTUC', 'OSPRENTUC'),
    ('OSPRM', 'OSPRM'),
    ('OSPRO', 'OSPRO'),
    ('OSPROTURA', 'OSPROTURA'),
    ('OSPS PREVENCION', 'OSPS PREVENCION'),
    ('PARQUE SALUD', 'PARQUE SALUD'),
    ('PREMEDICA', 'PREMEDICA'),
    ('PRESTADORES SANATORIALES', 'PRESTADORES SANATORIALES'),
    ('PRIMED', 'PRIMED'),
    ('PRIVAMED', 'PRIVAMED'),
    ('OSPS MERCEDES', 'OSPS MERCEDES'),
    ('OSPSESBA', 'OSPSESBA'),
    ('OSPSIP', 'OSPSIP'),
    ('OSPTA', 'OSPTA'),
    ('OSPTV', 'OSPTV'),
    ('OSPUAYE', 'OSPUAYE'),
    ('OSRGA', 'OSRGA'),
    ('OSRJA', 'OSRJA'),
    ('OSRM', 'OSRM'),
    ('MC SALUD', 'MC SALUD'),
    ('SUPERCO', 'SUPERCO'),
    ('SOREMER', 'SOREMER'),
    ('OSSA', 'OSSA'),
    ('OSSACRA', 'OSSACRA'),
    ('OSSB', 'OSSB'),
    ('SANTA CLARA', 'SANTA CLARA'),
    ('SOCIEDAD ITALIANA DE BENEFICENCIA', 'SOCIEDAD ITALIANA DE BENEFICENCIA'),
    ('OSSIMRA', 'OSSIMRA'),
    ('OSSOELSAC', 'OSSOELSAC'),
    ('OSSPYFER', 'OSSPYFER'),
    ('SABER SA', 'SABER SA'),
    ('SAJU SRL', 'SAJU SRL'),
    ('SCIS SA', 'SCIS SA'),
    ('OSTAD', 'OSTAD'),
    ('OSTAMMA', 'OSTAMMA'),
    ('OSTC', 'OSTC'),
    ('OSTECF', 'OSTECF'),
    ('OSTEE', 'OSTEE'),
    ('OSTEL', 'OSTEL'),
    ('OSTEP', 'OSTEP'),
    ('OSTES', 'OSTES'),
    ('OSTIG', 'OSTIG'),
    ('OSTP', 'OSTP'),
    ('OSTPBA', 'OSTPBA'),
    ('OSTPCHPYARA', 'OSTPCHPYARA'),
    ('OSTRAC', 'OSTRAC'),
    ('OSTSA', 'OSTSA'),
    ('OSTVA', 'OSTVA'),
    ('OSTVENDRA', 'OSTVENDRA'),
    ('OSTVLA', 'OSTVLA'),
    ('OSUCI', 'OSUCI'),
    ('OSUOMRA', 'OSUOMRA'),
    ('OSUTI', 'OSUTI'),
    ('OSV', 'OSV'),
    ('OSVARA', 'OSVARA'),
    ('OSVAS', 'OSVAS'),
    ('VITAS SA', 'VITAS SA'),
    ('OSVVRA / ANDAR', 'OSVVRA / ANDAR'),
    ('OSYC', 'OSYC'),
    ('OSYPF', 'OSYPF'),
    ('SANOS / NATIVUS', 'SANOS / NATIVUS'),
    ('SERVESALUD', 'SERVESALUD'),
    ('SALUD PROFESIONAL Y TECNOLOGICA', 'SALUD PROFESIONAL Y TECNOLOGICA'),
    ('UPFPARA', 'UPFPARA'),
    ('WHOPE', 'WHOPE')
) AS v(sigla, nombre_completo)
WHERE p."nombre" = v.sigla;
