-- CreateTable
CREATE TABLE "Prepaga" (
    "id" TEXT NOT NULL,
    "nombre" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Prepaga_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Prepaga_nombre_key" ON "Prepaga"("nombre");

-- Seed: columna "Sigla / Alias" de semio360_obras_sociales_prepagas_argentina.xlsx
INSERT INTO "Prepaga" ("id", "nombre") VALUES
    (gen_random_uuid()::text, 'PARTICULAR'),
    (gen_random_uuid()::text, 'ACCORD SALUD'),
    (gen_random_uuid()::text, 'AVALIAN'),
    (gen_random_uuid()::text, 'BOREAL'),
    (gen_random_uuid()::text, 'BRISTOL'),
    (gen_random_uuid()::text, 'CEMIC'),
    (gen_random_uuid()::text, 'EMERGENCIAS'),
    (gen_random_uuid()::text, 'ESENCIAL'),
    (gen_random_uuid()::text, 'FEDERADA SALUD'),
    (gen_random_uuid()::text, 'GALENO'),
    (gen_random_uuid()::text, 'HOMINIS'),
    (gen_random_uuid()::text, 'HOSPITAL ALEMAN'),
    (gen_random_uuid()::text, 'HOSPITAL AUSTRAL'),
    (gen_random_uuid()::text, 'JERARQUICOS SALUD'),
    (gen_random_uuid()::text, 'MEDICUS'),
    (gen_random_uuid()::text, 'MEDIFE'),
    (gen_random_uuid()::text, 'OMINT'),
    (gen_random_uuid()::text, 'OSDE'),
    (gen_random_uuid()::text, 'PREVENCION'),
    (gen_random_uuid()::text, 'SANCOR'),
    (gen_random_uuid()::text, 'SMG'),
    (gen_random_uuid()::text, 'SIPSSA'),
    (gen_random_uuid()::text, 'PAMI / INSSJP'),
    (gen_random_uuid()::text, 'IOMA'),
    (gen_random_uuid()::text, 'IAPOS'),
    (gen_random_uuid()::text, 'IOSCOR'),
    (gen_random_uuid()::text, 'APROSS'),
    (gen_random_uuid()::text, 'OSEP'),
    (gen_random_uuid()::text, 'OSEF'),
    (gen_random_uuid()::text, 'IOSPER'),
    (gen_random_uuid()::text, 'IPROSS'),
    (gen_random_uuid()::text, 'ISSN'),
    (gen_random_uuid()::text, 'IPS'),
    (gen_random_uuid()::text, 'ISJ'),
    (gen_random_uuid()::text, 'INSSSEP'),
    (gen_random_uuid()::text, 'IASEP'),
    (gen_random_uuid()::text, 'SEROS'),
    (gen_random_uuid()::text, 'SEMPRE'),
    (gen_random_uuid()::text, 'ObSBA'),
    (gen_random_uuid()::text, 'IOSFA'),
    (gen_random_uuid()::text, 'OSPJN'),
    (gen_random_uuid()::text, 'DAS'),
    (gen_random_uuid()::text, 'DOSUBA'),
    (gen_random_uuid()::text, 'DASPU'),
    (gen_random_uuid()::text, 'UNION PERSONAL'),
    (gen_random_uuid()::text, 'OSECAC'),
    (gen_random_uuid()::text, 'OSPRERA'),
    (gen_random_uuid()::text, 'OSPE'),
    (gen_random_uuid()::text, 'OSUTHGRA'),
    (gen_random_uuid()::text, 'OSPLAD'),
    (gen_random_uuid()::text, 'UOCRA / CONSTRUIR SALUD'),
    (gen_random_uuid()::text, 'OSMATA'),
    (gen_random_uuid()::text, 'OSSEG'),
    (gen_random_uuid()::text, 'OSFATLYF'),
    (gen_random_uuid()::text, 'OSFE'),
    (gen_random_uuid()::text, 'OSFYMT'),
    (gen_random_uuid()::text, 'OSPSA / SANIDAD'),
    (gen_random_uuid()::text, 'OSPAT'),
    (gen_random_uuid()::text, 'ADOS ROSARIO'),
    (gen_random_uuid()::text, 'AMCI'),
    (gen_random_uuid()::text, 'AMFFA'),
    (gen_random_uuid()::text, 'AMPAR'),
    (gen_random_uuid()::text, 'AMPES'),
    (gen_random_uuid()::text, 'AMUKRA'),
    (gen_random_uuid()::text, 'AMUR'),
    (gen_random_uuid()::text, 'APDIS'),
    (gen_random_uuid()::text, 'APDJIC'),
    (gen_random_uuid()::text, 'APSOT'),
    (gen_random_uuid()::text, 'ASE'),
    (gen_random_uuid()::text, 'ASSPE'),
    (gen_random_uuid()::text, 'DITEM'),
    (gen_random_uuid()::text, 'FAA'),
    (gen_random_uuid()::text, 'FEDECAMARAS'),
    (gen_random_uuid()::text, 'FRUTOS'),
    (gen_random_uuid()::text, 'JOHNSON'),
    (gen_random_uuid()::text, 'LUIS PASTEUR'),
    (gen_random_uuid()::text, 'O.S.A.M.O.C'),
    (gen_random_uuid()::text, 'O.S.A.P.S.E'),
    (gen_random_uuid()::text, 'O.S.PE.COR'),
    (gen_random_uuid()::text, 'O.S.PE.TAX.R'),
    (gen_random_uuid()::text, 'O.S.PERS.A.A.M.S.'),
    (gen_random_uuid()::text, 'O.S.S.U.R.R.B.A.C'),
    (gen_random_uuid()::text, 'O.S.T.A.C.C'),
    (gen_random_uuid()::text, 'O.S.T.C.A.R.A.'),
    (gen_random_uuid()::text, 'O.S.TAX.B.A'),
    (gen_random_uuid()::text, 'OPDEA'),
    (gen_random_uuid()::text, 'OPZC'),
    (gen_random_uuid()::text, 'GEA SA'),
    (gen_random_uuid()::text, 'ROI SA'),
    (gen_random_uuid()::text, 'OS.PE.PRI'),
    (gen_random_uuid()::text, 'APRES SA'),
    (gen_random_uuid()::text, 'OSA AERONAVEGANTES'),
    (gen_random_uuid()::text, 'OSA ACTORES'),
    (gen_random_uuid()::text, 'OSA ACTORES 2'),
    (gen_random_uuid()::text, 'OSADEF'),
    (gen_random_uuid()::text, 'OSADRA'),
    (gen_random_uuid()::text, 'OSAF'),
    (gen_random_uuid()::text, 'OSAGO'),
    (gen_random_uuid()::text, 'OSALARA'),
    (gen_random_uuid()::text, 'OSAM'),
    (gen_random_uuid()::text, 'OSAMF'),
    (gen_random_uuid()::text, 'OSAMM'),
    (gen_random_uuid()::text, 'OSAMMVC'),
    (gen_random_uuid()::text, 'OSAMP'),
    (gen_random_uuid()::text, 'OSAMS'),
    (gen_random_uuid()::text, 'OSAOS 1'),
    (gen_random_uuid()::text, 'OSAOS 2'),
    (gen_random_uuid()::text, 'OSAOS 3'),
    (gen_random_uuid()::text, 'OSAP ACEROS PARANA'),
    (gen_random_uuid()::text, 'OSAPL'),
    (gen_random_uuid()::text, 'OSAPM'),
    (gen_random_uuid()::text, 'OSAPMCBA'),
    (gen_random_uuid()::text, 'OSARP'),
    (gen_random_uuid()::text, 'ANDESALUD'),
    (gen_random_uuid()::text, 'AGRUPACION SANATORIAL SUR'),
    (gen_random_uuid()::text, 'ASISTENCIA SANITARIA INTEGRAL'),
    (gen_random_uuid()::text, 'ADMINISTRAR SALUD'),
    (gen_random_uuid()::text, 'ASSISTENCIAL SALUD'),
    (gen_random_uuid()::text, 'AMSTERDAM SALUD'),
    (gen_random_uuid()::text, 'OSBA'),
    (gen_random_uuid()::text, 'OSBARA'),
    (gen_random_uuid()::text, 'BIENESTAR SALUD'),
    (gen_random_uuid()::text, 'BONMED'),
    (gen_random_uuid()::text, 'OSCA'),
    (gen_random_uuid()::text, 'OSCAMGLYP'),
    (gen_random_uuid()::text, 'OSCAPBAQFLU'),
    (gen_random_uuid()::text, 'OSCCP'),
    (gen_random_uuid()::text, 'OSCE'),
    (gen_random_uuid()::text, 'OSCEA'),
    (gen_random_uuid()::text, 'OSCEP'),
    (gen_random_uuid()::text, 'OSCHOCA'),
    (gen_random_uuid()::text, 'OSCMJ'),
    (gen_random_uuid()::text, 'OSCML'),
    (gen_random_uuid()::text, 'OSCMM'),
    (gen_random_uuid()::text, 'OSCOEMA'),
    (gen_random_uuid()::text, 'OSCOMM'),
    (gen_random_uuid()::text, 'OSCONARA'),
    (gen_random_uuid()::text, 'OSCRAIA'),
    (gen_random_uuid()::text, 'CARE SALUD'),
    (gen_random_uuid()::text, 'CORSAL'),
    (gen_random_uuid()::text, 'CYNTHIOS SALUD'),
    (gen_random_uuid()::text, 'OSCTC'),
    (gen_random_uuid()::text, 'OSDAA'),
    (gen_random_uuid()::text, 'OSDEL'),
    (gen_random_uuid()::text, 'OSDEM'),
    (gen_random_uuid()::text, 'OSDEPYM'),
    (gen_random_uuid()::text, 'OSDIC'),
    (gen_random_uuid()::text, 'OSDIPP'),
    (gen_random_uuid()::text, 'OSDO'),
    (gen_random_uuid()::text, 'OSDOP'),
    (gen_random_uuid()::text, 'OSEADI'),
    (gen_random_uuid()::text, 'OSEAM'),
    (gen_random_uuid()::text, 'OSEDA'),
    (gen_random_uuid()::text, 'OSEDEIV'),
    (gen_random_uuid()::text, 'OSEIV'),
    (gen_random_uuid()::text, 'OSEMM'),
    (gen_random_uuid()::text, 'EMINENTE MEDICINAL'),
    (gen_random_uuid()::text, 'OSEN'),
    (gen_random_uuid()::text, 'OSEPC'),
    (gen_random_uuid()::text, 'OSEPJ'),
    (gen_random_uuid()::text, 'ENSALUD'),
    (gen_random_uuid()::text, 'OSETRA'),
    (gen_random_uuid()::text, 'OSETYA'),
    (gen_random_uuid()::text, 'OSFAS'),
    (gen_random_uuid()::text, 'OSFATUN'),
    (gen_random_uuid()::text, 'OSFFENTOS'),
    (gen_random_uuid()::text, 'OSFGP'),
    (gen_random_uuid()::text, 'OSFOT'),
    (gen_random_uuid()::text, 'OSFYB'),
    (gen_random_uuid()::text, 'OSFYHC'),
    (gen_random_uuid()::text, 'OSGMG'),
    (gen_random_uuid()::text, 'GRUPO MEDICO INCAS'),
    (gen_random_uuid()::text, 'GERMED'),
    (gen_random_uuid()::text, 'GILSA'),
    (gen_random_uuid()::text, 'GRUPO DDM'),
    (gen_random_uuid()::text, 'HOSPITAL ALEMAN RNAS'),
    (gen_random_uuid()::text, 'HOSPITAL BRITANICO'),
    (gen_random_uuid()::text, 'OSIAD'),
    (gen_random_uuid()::text, 'OSIM'),
    (gen_random_uuid()::text, 'OSIPA'),
    (gen_random_uuid()::text, 'OSITAC'),
    (gen_random_uuid()::text, 'OSLYF'),
    (gen_random_uuid()::text, 'OSLYF PATAGONIA'),
    (gen_random_uuid()::text, 'MET-CORDOBA'),
    (gen_random_uuid()::text, 'OSMA'),
    (gen_random_uuid()::text, 'OSMAD'),
    (gen_random_uuid()::text, 'MEDYCIN ARGENTINO'),
    (gen_random_uuid()::text, 'OSME'),
    (gen_random_uuid()::text, 'OSMEDICA'),
    (gen_random_uuid()::text, 'OSMISS'),
    (gen_random_uuid()::text, 'OSMITA'),
    (gen_random_uuid()::text, 'MUTUAL MEDICA CONCORDIA'),
    (gen_random_uuid()::text, 'OSMMEDT'),
    (gen_random_uuid()::text, 'OSMPA'),
    (gen_random_uuid()::text, 'OSMPC'),
    (gen_random_uuid()::text, 'MEDICINA PRIVADA SRL'),
    (gen_random_uuid()::text, 'MEMED'),
    (gen_random_uuid()::text, 'MEDICAL SERVICIOS DE SALUD'),
    (gen_random_uuid()::text, 'OSMTT'),
    (gen_random_uuid()::text, 'NOBIS'),
    (gen_random_uuid()::text, 'OSOC'),
    (gen_random_uuid()::text, 'OSOCNA'),
    (gen_random_uuid()::text, 'OSOEF'),
    (gen_random_uuid()::text, 'OSOETSYLARA'),
    (gen_random_uuid()::text, 'OSOPP'),
    (gen_random_uuid()::text, 'OSOSS'),
    (gen_random_uuid()::text, 'PLENIMEDICAL'),
    (gen_random_uuid()::text, 'OSPA PORTUARIOS'),
    (gen_random_uuid()::text, 'OSPA AERONAUTICO'),
    (gen_random_uuid()::text, 'OSPA AZUCAR 1'),
    (gen_random_uuid()::text, 'OSPA AZUCAR 2'),
    (gen_random_uuid()::text, 'OSPA PORTUARIOS 2'),
    (gen_random_uuid()::text, 'OSPA-VIAL'),
    (gen_random_uuid()::text, 'OSPAA'),
    (gen_random_uuid()::text, 'OSPACA 1'),
    (gen_random_uuid()::text, 'OSPACA 2'),
    (gen_random_uuid()::text, 'OSPACP'),
    (gen_random_uuid()::text, 'OSPADEP'),
    (gen_random_uuid()::text, 'OSPAF'),
    (gen_random_uuid()::text, 'OSPAGA'),
    (gen_random_uuid()::text, 'OSPAIL'),
    (gen_random_uuid()::text, 'OSPAÑA'),
    (gen_random_uuid()::text, 'OSPAP'),
    (gen_random_uuid()::text, 'OSPATCA'),
    (gen_random_uuid()::text, 'OSPAV'),
    (gen_random_uuid()::text, 'OSPBL'),
    (gen_random_uuid()::text, 'OSPCR'),
    (gen_random_uuid()::text, 'OSPCRA'),
    (gen_random_uuid()::text, 'OSPCSPMYA'),
    (gen_random_uuid()::text, 'OSPCYD'),
    (gen_random_uuid()::text, 'OSPDESBA'),
    (gen_random_uuid()::text, 'OSPDI'),
    (gen_random_uuid()::text, 'OSPE 1'),
    (gen_random_uuid()::text, 'OSPE ESCRIBANOS'),
    (gen_random_uuid()::text, 'OSPEA'),
    (gen_random_uuid()::text, 'OSPEC'),
    (gen_random_uuid()::text, 'OSPECA'),
    (gen_random_uuid()::text, 'OSPEDICI'),
    (gen_random_uuid()::text, 'OSPEDYB'),
    (gen_random_uuid()::text, 'OSPEDYC'),
    (gen_random_uuid()::text, 'OSPEF Y EPCA'),
    (gen_random_uuid()::text, 'OSPEJ'),
    (gen_random_uuid()::text, 'OSPEL'),
    (gen_random_uuid()::text, 'OSPEMER'),
    (gen_random_uuid()::text, 'OSPEMOM'),
    (gen_random_uuid()::text, 'OSPENA'),
    (gen_random_uuid()::text, 'OSPEP 1'),
    (gen_random_uuid()::text, 'OSPEP 2'),
    (gen_random_uuid()::text, 'OSPEP 3'),
    (gen_random_uuid()::text, 'OSPEP DIRECCION'),
    (gen_random_uuid()::text, 'OSPEPBA'),
    (gen_random_uuid()::text, 'OSPEPRI / MEOPP'),
    (gen_random_uuid()::text, 'OSPERCIN'),
    (gen_random_uuid()::text, 'OSPERYH'),
    (gen_random_uuid()::text, 'OSPERYHRA'),
    (gen_random_uuid()::text, 'OSPES'),
    (gen_random_uuid()::text, 'OSPESA'),
    (gen_random_uuid()::text, 'OSPESCA'),
    (gen_random_uuid()::text, 'OSPESCHA'),
    (gen_random_uuid()::text, 'OSPESGA'),
    (gen_random_uuid()::text, 'OSPESGYPE'),
    (gen_random_uuid()::text, 'OSPETAX'),
    (gen_random_uuid()::text, 'OSPETELCO'),
    (gen_random_uuid()::text, 'OSPEVIC'),
    (gen_random_uuid()::text, 'OSPFS'),
    (gen_random_uuid()::text, 'OSPG'),
    (gen_random_uuid()::text, 'OSPHGBAYSI'),
    (gen_random_uuid()::text, 'OSPIA 1'),
    (gen_random_uuid()::text, 'OSPIA 2'),
    (gen_random_uuid()::text, 'OSPIC 1'),
    (gen_random_uuid()::text, 'OSPIC 2'),
    (gen_random_uuid()::text, 'OSPIC SANTA FE'),
    (gen_random_uuid()::text, 'OSPICA'),
    (gen_random_uuid()::text, 'OSPICAL'),
    (gen_random_uuid()::text, 'OSPICHA'),
    (gen_random_uuid()::text, 'OSPIDA'),
    (gen_random_uuid()::text, 'OSPIF 1'),
    (gen_random_uuid()::text, 'OSPIF 2'),
    (gen_random_uuid()::text, 'OSPIFSE'),
    (gen_random_uuid()::text, 'OSPIG'),
    (gen_random_uuid()::text, 'OSPIHMP'),
    (gen_random_uuid()::text, 'OSPIL'),
    (gen_random_uuid()::text, 'OSPILM'),
    (gen_random_uuid()::text, 'OSPIM 1'),
    (gen_random_uuid()::text, 'OSPIM 2'),
    (gen_random_uuid()::text, 'OSPIN 1'),
    (gen_random_uuid()::text, 'OSPIN 2'),
    (gen_random_uuid()::text, 'OSPIP 1'),
    (gen_random_uuid()::text, 'OSPIP 2'),
    (gen_random_uuid()::text, 'OSPIP 3'),
    (gen_random_uuid()::text, 'OSPIQYP'),
    (gen_random_uuid()::text, 'OSPIS'),
    (gen_random_uuid()::text, 'OSPIT 1'),
    (gen_random_uuid()::text, 'OSPIT 2'),
    (gen_random_uuid()::text, 'OSPIT 3'),
    (gen_random_uuid()::text, 'OSPIV 1'),
    (gen_random_uuid()::text, 'OSPIV 2'),
    (gen_random_uuid()::text, 'OSPJC'),
    (gen_random_uuid()::text, 'OSPJT'),
    (gen_random_uuid()::text, 'OSPL'),
    (gen_random_uuid()::text, 'OSPLA'),
    (gen_random_uuid()::text, 'OSPM 1'),
    (gen_random_uuid()::text, 'OSPM 2'),
    (gen_random_uuid()::text, 'OSPM 3'),
    (gen_random_uuid()::text, 'OSPMA'),
    (gen_random_uuid()::text, 'OSPMJ'),
    (gen_random_uuid()::text, 'OSPMM'),
    (gen_random_uuid()::text, 'OSPMS'),
    (gen_random_uuid()::text, 'OSPMT'),
    (gen_random_uuid()::text, 'OSPOCE'),
    (gen_random_uuid()::text, 'OSPP'),
    (gen_random_uuid()::text, 'OSPPB 1'),
    (gen_random_uuid()::text, 'OSPPB 2'),
    (gen_random_uuid()::text, 'OSPPCYQ'),
    (gen_random_uuid()::text, 'OSPPEA'),
    (gen_random_uuid()::text, 'OSPPM PRENSA'),
    (gen_random_uuid()::text, 'OSPPM PUERTOS'),
    (gen_random_uuid()::text, 'OSPPRA'),
    (gen_random_uuid()::text, 'OSPRB'),
    (gen_random_uuid()::text, 'OSPREME'),
    (gen_random_uuid()::text, 'OSPREN'),
    (gen_random_uuid()::text, 'OSPRENTUC'),
    (gen_random_uuid()::text, 'OSPRM'),
    (gen_random_uuid()::text, 'OSPRO'),
    (gen_random_uuid()::text, 'OSPROTURA'),
    (gen_random_uuid()::text, 'OSPS PREVENCION'),
    (gen_random_uuid()::text, 'PARQUE SALUD'),
    (gen_random_uuid()::text, 'PREMEDICA'),
    (gen_random_uuid()::text, 'PRESTADORES SANATORIALES'),
    (gen_random_uuid()::text, 'PRIMED'),
    (gen_random_uuid()::text, 'PRIVAMED'),
    (gen_random_uuid()::text, 'OSPS MERCEDES'),
    (gen_random_uuid()::text, 'OSPSESBA'),
    (gen_random_uuid()::text, 'OSPSIP'),
    (gen_random_uuid()::text, 'OSPTA'),
    (gen_random_uuid()::text, 'OSPTV'),
    (gen_random_uuid()::text, 'OSPUAYE'),
    (gen_random_uuid()::text, 'OSRGA'),
    (gen_random_uuid()::text, 'OSRJA'),
    (gen_random_uuid()::text, 'OSRM'),
    (gen_random_uuid()::text, 'MC SALUD'),
    (gen_random_uuid()::text, 'SUPERCO'),
    (gen_random_uuid()::text, 'SOREMER'),
    (gen_random_uuid()::text, 'OSSA'),
    (gen_random_uuid()::text, 'OSSACRA'),
    (gen_random_uuid()::text, 'OSSB'),
    (gen_random_uuid()::text, 'SANTA CLARA'),
    (gen_random_uuid()::text, 'SOCIEDAD ITALIANA DE BENEFICENCIA'),
    (gen_random_uuid()::text, 'OSSIMRA'),
    (gen_random_uuid()::text, 'OSSOELSAC'),
    (gen_random_uuid()::text, 'OSSPYFER'),
    (gen_random_uuid()::text, 'SABER SA'),
    (gen_random_uuid()::text, 'SAJU SRL'),
    (gen_random_uuid()::text, 'SCIS SA'),
    (gen_random_uuid()::text, 'OSTAD'),
    (gen_random_uuid()::text, 'OSTAMMA'),
    (gen_random_uuid()::text, 'OSTC'),
    (gen_random_uuid()::text, 'OSTECF'),
    (gen_random_uuid()::text, 'OSTEE'),
    (gen_random_uuid()::text, 'OSTEL'),
    (gen_random_uuid()::text, 'OSTEP'),
    (gen_random_uuid()::text, 'OSTES'),
    (gen_random_uuid()::text, 'OSTIG'),
    (gen_random_uuid()::text, 'OSTP'),
    (gen_random_uuid()::text, 'OSTPBA'),
    (gen_random_uuid()::text, 'OSTPCHPYARA'),
    (gen_random_uuid()::text, 'OSTRAC'),
    (gen_random_uuid()::text, 'OSTSA'),
    (gen_random_uuid()::text, 'OSTVA'),
    (gen_random_uuid()::text, 'OSTVENDRA'),
    (gen_random_uuid()::text, 'OSTVLA'),
    (gen_random_uuid()::text, 'OSUCI'),
    (gen_random_uuid()::text, 'OSUOMRA'),
    (gen_random_uuid()::text, 'OSUTI'),
    (gen_random_uuid()::text, 'OSV'),
    (gen_random_uuid()::text, 'OSVARA'),
    (gen_random_uuid()::text, 'OSVAS'),
    (gen_random_uuid()::text, 'VITAS SA'),
    (gen_random_uuid()::text, 'OSVVRA / ANDAR'),
    (gen_random_uuid()::text, 'OSYC'),
    (gen_random_uuid()::text, 'OSYPF'),
    (gen_random_uuid()::text, 'SANOS / NATIVUS'),
    (gen_random_uuid()::text, 'SERVESALUD'),
    (gen_random_uuid()::text, 'SALUD PROFESIONAL Y TECNOLOGICA'),
    (gen_random_uuid()::text, 'UPFPARA'),
    (gen_random_uuid()::text, 'WHOPE');
