-- CreateEnum
CREATE TYPE "Especialidad" AS ENUM ('CLINICA_MEDICA', 'MEDICINA_FAMILIAR_GENERAL', 'PEDIATRIA', 'GINECOLOGIA', 'OBSTETRICIA', 'CARDIOLOGIA', 'DERMATOLOGIA', 'ENDOCRINOLOGIA', 'GASTROENTEROLOGIA', 'TRAUMATOLOGIA_Y_ORTOPEDIA', 'OFTALMOLOGIA', 'OTORRINOLARINGOLOGIA', 'NEUROLOGIA', 'PSIQUIATRIA', 'UROLOGIA', 'REUMATOLOGIA', 'NEUMONOLOGIA', 'ALERGIA_E_INMUNOLOGIA', 'INFECTOLOGIA', 'NEFROLOGIA', 'HEMATOLOGIA', 'ONCOLOGIA', 'GERIATRIA', 'NUTRICION', 'FLEBOLOGIA', 'DIABETOLOGIA', 'MEDICINA_DEL_DEPORTE', 'MEDICINA_FISICA_Y_REHABILITACION_FISIATRIA', 'MEDICINA_REPRODUCTIVA_FERTILIDAD', 'MEDICINA_DEL_DOLOR', 'MEDICINA_PALIATIVA', 'HEPATOLOGIA', 'COLOPROCTOLOGIA', 'MASTOLOGIA', 'ANDROLOGIA', 'CARDIOLOGIA_INFANTIL', 'NEUROLOGIA_INFANTIL', 'ENDOCRINOLOGIA_INFANTIL', 'GASTROENTEROLOGIA_INFANTIL', 'NEUMONOLOGIA_INFANTIL', 'NEFROLOGIA_INFANTIL', 'REUMATOLOGIA_INFANTIL', 'ALERGIA_E_INMUNOLOGIA_INFANTIL', 'INFECTOLOGIA_INFANTIL', 'PSIQUIATRIA_INFANTIL_Y_ADOLESCENTE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "especialidad" "Especialidad";

-- Backfill: los médicos que ya existían al agregar este campo quedan con
-- "Clínica Médica" en vez de NULL.
UPDATE "User" SET "especialidad" = 'CLINICA_MEDICA' WHERE "role" = 'DOCTOR' AND "especialidad" IS NULL;
